### ISSUE TITLE
Want to use your dataset for research purpose.

### ISSUE THREAD

**Issue by ShobhitUP** [rajeshmore1/Capstone-Project-2#6]
Hii
My name is Shobhit Srivastava. I am doing PhD in Computer Science and want to use your dataset for research purposes.
I will give you full credit and citations in my work. Kindly allow.

**Comment by rajeshmore1** [comment]
Hi Shobhit, Yes you can use this repo and the dataset for your research work. Once completed your research, please share the screenshot of citation to er.rajeshmore@gmail.com

Thanks,
Rajesh
